"""Presentation figures for the final deck.

The analysis figures in `reports/figures/` are built for a reader who can stop
and study them. A slide has to land from the back of a room in two seconds, so
a few of them are rebuilt here with plain-English labels and the noise removed.

Only figures that need rebuilding live here. `phase6_irs_validation.png` already
reads well on a slide and is used as-is.

Usage
-----
    python3 scripts/make_deck_figures.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.ticker import FuncFormatter

ROOT = Path(__file__).resolve().parent.parent
TWINS = ROOT / "reports" / "twins"
FIGURES = ROOT / "reports" / "figures"

# Matches the palette already used by phase6_irs_validation.png so the deck's
# chart cards read as one family.
PAPER = "#FAFAF8"
INK = "#222222"
MUTED = "#555555"
GRID = "#D9D9D4"


def twin_gaps_by_decile() -> Path:
    """Slide 12 — the three findings, one panel, plain English.

    Replaces panel (c) of `phase5_twin_gaps.png`. The two histogram panels are
    dropped (unreadable at projection size) and `filing_status` is dropped
    deliberately: its mean is -2.90 and its median +2.11, so a single line
    through its decile means would average away a genuinely bimodal result.
    The marriage series is the *supported* direction only -- joint -> single has
    zero training examples in the target region and is not quoted.
    """
    decile = pd.read_csv(TWINS / "twin_gap_by_income_decile.csv", index_col=0)

    series = [
        ("dominant_income_source", "Paycheck → investments", "#7B4EA8", "^"),
        ("marriage (supported only)", "Single → married filing jointly", "#2E7D4F", "o"),
        ("dependents", "Adding two children", "#356AA0", "s"),
    ]

    fig, ax = plt.subplots(figsize=(15.5, 8.0))
    fig.patch.set_facecolor(PAPER)
    ax.set_facecolor(PAPER)

    x = range(len(decile))
    for column, label, color, marker in series:
        ax.plot(x, decile[column].to_numpy(dtype=float), label=label, color=color,
                marker=marker, linewidth=2.4, markersize=7, zorder=3)

    ax.axhline(0, color="#777777", linewidth=1.0, zorder=1)
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.grid(axis="x", visible=False)

    # Dollar signs must be escaped or matplotlib reads the pair as mathtext and
    # renders the span between them in italic with the signs swallowed.
    labels = [
        rf"\${row.income_from / 1000:,.0f}k–\${row.income_to / 1000:,.0f}k"
        for row in decile.itertuples()
    ]
    labels[-1] = r"\$214k+"
    ax.set_xticks(list(x), labels, rotation=32, ha="right", fontsize=12)
    ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:+.0f}"))
    ax.tick_params(axis="y", labelsize=13, length=0)

    ax.set_ylabel("Change in effective tax rate (percentage points)", fontsize=13)
    ax.set_xlabel("Total income, lowest tenth of filers to highest", fontsize=13, labelpad=10)
    ax.set_title(
        "Hold everything constant, flip one attribute — what changes",
        loc="left", fontsize=20, fontweight="semibold", pad=26, color=INK,
    )
    ax.text(0, 1.015,
            "All 12,247 held-out filers · each point is the mean change for that income tenth "
            "· below zero means the flip lowers the rate",
            transform=ax.transAxes, ha="left", va="bottom", fontsize=12, color=MUTED)

    # Upper right is the only quadrant all three series stay out of.
    ax.legend(frameon=False, loc="upper right", fontsize=14, ncol=1)
    for spine in ("top", "right", "left"):
        ax.spines[spine].set_visible(False)
    ax.spines["bottom"].set_color("#999999")

    fig.text(0.062, 0.015,
             "Counterfactual twins generated by the model, not observed filers. "
             "Marriage shows the single/head-of-household → joint direction only; "
             "the reverse has no training support.",
             fontsize=10.5, color=MUTED)

    fig.tight_layout(rect=(0, 0.035, 1, 1))
    out = FIGURES / "slide12_twin_gaps.png"
    fig.savefig(out, dpi=200, facecolor=PAPER)
    plt.close(fig)
    return out


if __name__ == "__main__":
    print("wrote", twin_gaps_by_decile().relative_to(ROOT))
